# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tbergkul <tbergkul@student.hive.fi>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/07/24 13:49:27 by tbergkul          #+#    #+#              #
#    Updated: 2019/07/25 17:52:50 by tbergkul         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_cat.c
FILE = ft_cat

all:
	gcc -Wall -Wextra -Werror -o $(FILE) $(NAME)
	
clean:
	/bin/rm -f a.out

fclean: 
	/bin/rm -f $(FILE)
